name: libs/ngrx-hateoas

on: [push, pull_request]

jobs:
  test_and_build:
    name: 'Test and Build'
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Node.js
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Restore dependencies
      - name: Restore dependencies
        run: |
          npm install

      # Execute all unit tests
      - name: Execute tests
        run: |
          npm run test:github

      # Build library
      - name: Build library
        run: |
          npm run build
